#version: "3.7"
#services:
#  api_service:
#    build: .
#    restart: always
#    ports:
#      - 9990:9990
#    depends_on:
#      - postgres_db
#    links:
#      - postgres_db:database
#  postgres_db:
#    image: "postgres:14"
#    restart: always
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_DB: your_database
#      POSTGRES_PASSWORD: root


# -----------------------------------

version: '3.1'
services:
  API:
    image: 'springboot-product.jar'
    ports:
      - 9990:9990
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/your_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSQL:
    image: "postgres:14"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=your_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5