version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 9990:9990
    depends_on:
      - postgres_db
    links:
      - postgres_db:database
  postgres_db:
    image: "postgres:14"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: your_database
      POSTGRES_PASSWORD: root